services:
  - postgresql
addons:
  postgresql: "9.6"
env:
  global:
    - URL=http://localhost:9000
    - PORT=9000

language: node_js
node_js:
  - stable
branches:
  only:
    - develop
install:
  - npm install
cache:
  directories:
    - node_modules
before_script:
  - psql -c 'create database freementor;' -U postgres
script:
  - npm test
after_success:
  - npm run coverage